### ISSUE TITLE
Tombstone messages are being ignored (and not handled as per documentation)

### ISSUE THREAD

**Issue by itssrihere** [Aiven-Open/jdbc-connector-for-apache-kafka#287]
Hi,

The Aiven documentation here: https://aiven.io/docs/products/kafka/kafka-connect/howto/jdbc-sink suggests that tombstone messages will cause the corresponding rows in the underlying table to be deleted.

But that does not appear to be the case. It looks like tombstone messages are currently being ignored (silently)? It is not clear why the documentation (from above) would suggest a different behavior. Would appreciate it if someone could help in this regard.

**Comment by itssrihere** [comment]
Just wanted to follow up in this regard. Any thoughts or insights would be appreciated!

**Comment by jeqo** [comment]
@itssrihere thanks for reporting this! 
Could you provide the following info to look deeper into this: 
- Connector version
- Connector configuration (sample) 
- Sample data: input message and row not being deleted

**Comment by itssrihere** [comment]
@jeqo - Thank you for you response. I did see #165 previously. Unless I am mistaken, the open MR in that issue appears to be to potentially skip (log warn, or even error or fail) upon receiving tombstone messages (with a key and a null value). 

Are there plans to support the handling of tombstone messages similar to how the confluent JDBC connector handles them? - that is cause the corresponding rows from the database tables to be deleted?

**Comment by matuagarwal** [comment]
@jeqo - We need this feature as well and wanted to check if you would be open to accept PR for same

**Comment by jeqo** [comment]
@matuagarwal, great! This is definitely a useful feature. Feel free to open a PR and ping me for reviewing.
@itssrihere you may also want to review it :)

**Comment by jeqo** [comment]
I'll close this one, lmk if there's anything missing.

**Comment by Joel-hanson** [comment]
@jeqo we have raised a new PR that adds in this feature. https://github.com/Aiven-Open/jdbc-connector-for-apache-kafka/pull/302.
